### ISSUE TITLE
VectorFragment should be scoped to Fragment's View lifecycle

### ISSUE THREAD

**Issue by alan-rodriguez** [haroldadmin/Vector#21]
**Describe the bug**
The fragment's view is destroyed before `fragmentScope` is cancelled in `onDestroy()`, which can cause crashes if the renderer directly references any views. The usage of data binding in the sample fragments prevents this from happening, but consumers of the library may not be using data binding.

**Expected behavior**
Use [`viewLifecycleOwner.lifecycleScope` from lifecycle-runtime-ktx](https://developer.android.com/topic/libraries/architecture/coroutines#lifecyclescope) or manually manage `fragmentScope` according to the Fragment's View lifecycle.

**Comment by haroldadmin** [comment]
Thank you for bringing this up. I agree that the `renderer` method should be bound to the view lifecycle instead of the fragment lifecycle. However, changing `fragmentScope` would be a potentially breaking change.

As alternative, i can introduce a `viewScope` Coroutine scope to `VectorFragment` and bind the renderer method to it. Would this be an acceptable solution to you?

Under the hood `viewScope` can simply act as an alias for `viewLifecycleOwner.lifecycleScope`.
